import { BarChart3, ChartScatter, Filter } from 'lucide-react';
import { useCallback, useMemo, useState } from 'react';
import type { Data, Layout } from 'plotly.js';
import PlotCanvas from '../components/PlotCanvas';
import { Empty, Notice, PageHeader } from '../components/UI';
import type { Experiment, Measurement } from '../types';
import { comparableGroups, humanize } from '../utils';

export default function Explorer({ measurements, experiments, onSelect }: { measurements: Measurement[]; experiments: Experiment[]; onSelect: (measurement: Measurement) => void }) {
  const [includeCandidates, setIncludeCandidates] = useState(false); const [selectedKey, setSelectedKey] = useState(''); const [mode, setMode] = useState<'scatter' | 'histogram'>('scatter');
  const groups = useMemo(() => comparableGroups(measurements, includeCandidates), [measurements, includeCandidates]);
  const group = groups.find(item => item.key === selectedKey) ?? groups[0];
  const experimentMap = useMemo(() => new Map(experiments.map(item => [item.id, item])), [experiments]);
  const data = useMemo<Data[]>(() => {
    if (!group) return [];
    if (mode === 'histogram') return [{ type: 'histogram', x: group.values, marker: { color: '#0969da', line: { color: '#ffffff', width: 1 } }, hovertemplate: '%{x}<br>%{y} measurements<extra></extra>' }];
    return ['reported', 'digitized', 'derived'].map((origin, index) => {
      const ids = group.measurements.map((item, i) => ({ item, i })).filter(({ item }) => item.origin === origin);
      return { type: 'scatter', mode: 'markers', name: humanize(origin), x: ids.map(({ item }) => experimentMap.get(item.experiment_id)?.sample_label ?? item.experiment_id), y: ids.map(({ i }) => group.values[i]), customdata: ids.map(({ i }) => i), text: ids.map(({ item }) => `${humanize(item.status)} · ${experimentMap.get(item.experiment_id)?.doi ?? 'DOI not reported'}`), marker: { size: 11, color: ['#0969da', '#bf5b04', '#8250df'][index], line: { color: '#ffffff', width: 1.5 } }, hovertemplate: '%{x}<br>%{y}<br>%{text}<extra>%{fullData.name}</extra>' } as Data;
    }).filter(trace => (trace as { x: unknown[] }).x.length);
  }, [group, mode, experimentMap]);
  const layout = useMemo<Partial<Layout>>(() => ({ xaxis: { title: { text: mode === 'scatter' ? 'Experimental sample' : `${humanize(group?.outcome ?? '')} (${group?.unit ?? ''})` }, type: mode === 'scatter' ? 'category' : 'linear', gridcolor: '#d8dee4', automargin: true }, yaxis: { title: { text: mode === 'scatter' ? `${humanize(group?.outcome ?? '')} (${group?.unit ?? ''})` : 'Recorded measurements' }, gridcolor: '#d8dee4', automargin: true }, legend: { orientation: 'h', y: 1.15 }, bargap: 0.08 }), [group, mode]);
  const pointClick = useCallback((index: number) => { if (group?.measurements[index]) onSelect(group.measurements[index]); }, [group, onSelect]);
  const uniqueStudies = group ? new Set(group.measurements.map(item => experimentMap.get(item.experiment_id)?.study_family ?? item.experiment_id)).size : 0;
  return <><PageHeader eyebrow="EXPERIMENTAL LANDSCAPE" title="Explore comparable observations">Inspect real recorded values, separated by outcome, unit, method, statistic, time point and concentration basis.</PageHeader><div className="explorer-toolbar panel"><div className="filter-heading"><Filter size={18} /><strong>Comparability group</strong></div><select aria-label="Select comparability group" value={group?.key ?? ''} onChange={e => setSelectedKey(e.target.value)} disabled={!groups.length}>{!groups.length && <option value="">No comparable group available</option>}{groups.map(item => <option value={item.key} key={item.key}>{humanize(item.outcome)} · {item.unit} · {item.method} · {item.statistic} · {item.time} · {item.basis} ({item.values.length})</option>)}</select><label className="checkbox-label"><input type="checkbox" checked={includeCandidates} onChange={e => setIncludeCandidates(e.target.checked)} />Include unreviewed candidates</label></div>{includeCandidates && <Notice kind="warning">Candidate measurements have not been accepted. This view supports inspection and does not constitute validated inference.</Notice>}<Notice>Unknown units, methods or statistics, non-exact values and sampled curve points are excluded from these charts. Unreported time or basis remains labelled; confirm relevance before interpreting comparisons.</Notice>{group ? <><div className="metric-grid compact"><div className="metric"><span>Recorded measurements</span><strong>{group.values.length}</strong></div><div className="metric"><span>Study families</span><strong>{uniqueStudies}</strong></div><div className="metric"><span>Measurement method</span><strong className="metric-text">{group.method}</strong></div><div className="metric"><span>Time point</span><strong className="metric-text">{group.time}</strong></div></div><section className="panel chart-panel"><div className="section-heading"><div><h2>{humanize(group.outcome)}</h2><p className="small muted">{group.statistic} · {group.unit} · {group.basis}</p></div><div className="segmented"><button className={mode === 'scatter' ? 'active' : ''} onClick={() => setMode('scatter')}><ChartScatter size={15} />Samples</button><button className={mode === 'histogram' ? 'active' : ''} onClick={() => setMode('histogram')}><BarChart3 size={15} />Distribution</button></div></div><PlotCanvas data={data} layout={layout} onPoint={mode === 'scatter' ? pointClick : undefined} /><p className="chart-caption">{mode === 'scatter' ? 'Select a point to inspect its source evidence. ' : ''}The chart counts recorded measurements; it does not treat them as independent studies or pool effect estimates.</p></section></> : <section className="panel"><Empty icon={<ChartScatter size={31} />} title="Comparable observations are needed">Accept measurements with recorded units, methods and statistics in the evidence view. Their actual values will form the exploration groups here.</Empty></section>}</>;
}
