import { Check, Copy, Link, ShieldCheck, Users } from 'lucide-react';
import { useState } from 'react';
import { api } from '../api';
import type { Invitation, Member, Project } from '../types';
import { date } from '../utils';
import { Badge, Empty, Field, Notice, PageHeader } from '../components/UI';

export default function Team({ project, members }: { project: Project; members: Member[] }) {
  const [role, setRole] = useState<'editor' | 'reader'>('reader'); const [invitation, setInvitation] = useState<Invitation | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [copied, setCopied] = useState(false);
  const invite = async () => { setBusy(true); setError(''); setCopied(false); try { setInvitation(await api.invite(project.id, role)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Invitation creation failed.'); } finally { setBusy(false); } };
  const copy = async () => { if (!invitation) return; try { await navigator.clipboard.writeText(new URL(invitation.url, window.location.origin).href); setCopied(true); } catch { setError('Clipboard access is unavailable. Select and copy the invitation link below.'); } };
  return <><PageHeader eyebrow="PRIVATE COLLABORATION" title="A shared review, controlled access">Your workspace is private. Invite collaborators to inspect evidence or help adjudicate the review.</PageHeader><div className="two-column"><section className="panel"><div className="section-heading"><h2>Review members</h2><Users className="teal" size={24} /></div>{members.length ? <div className="member-list">{members.map((member, index) => <div className="member-row" key={member.id ?? member.user_id ?? index}><span className="avatar">{(member.login ?? member.name ?? 'M').charAt(0).toUpperCase()}</span><div><strong>{member.name ?? member.login ?? 'Review member'}</strong><small>{member.login ? `@${member.login}` : member.user_id ?? member.id}</small></div><Badge value={member.role} /></div>)}</div> : <Empty title="No member details were returned">Membership is checked by the server on every review and artifact request.</Empty>}</section><section className="panel"><div className="section-heading"><h2>Invite a collaborator</h2><ShieldCheck className="teal" size={24} /></div><p className="muted">Create a single-use link and share it with the intended collaborator. They sign in with GitHub before accepting.</p><Field label="Access level"><select value={role} onChange={e => setRole(e.target.value as 'editor' | 'reader')} disabled={project.role !== 'owner'}><option value="reader">Reader — inspect evidence and exports</option><option value="editor">Editor — upload, review and run analyses</option></select></Field><button className="button primary" disabled={busy || project.role !== 'owner'} onClick={() => void invite()}><Link size={16} />{busy ? 'Creating…' : 'Create invitation link'}</button>{project.role !== 'owner' && <p className="small muted">Only the owner can create invitations.</p>}{error && <Notice kind="warning">{error}</Notice>}{invitation && <div className="invitation-result"><Field label="Invitation link"><input readOnly value={new URL(invitation.url, window.location.origin).href} onFocus={e => e.target.select()} /></Field><div className="panel-footer"><small>Expires {date(invitation.expires_at)}</small><button className="button small" onClick={() => void copy()}>{copied ? <Check size={14} /> : <Copy size={14} />}{copied ? 'Copied' : 'Copy link'}</button></div></div>}</section></div></>;
}
