import { ArrowRight, CircleDollarSign, Pause, Play, RotateCcw } from 'lucide-react';
import { useState } from 'react';
import type { Document, Run } from '../types';
import { date, money, progressInfo } from '../utils';
import { Badge, Empty, Field, JsonDetails, Notice } from './UI';

export function RunForm({ documents, canEdit, busy, onStart }: { documents: Document[]; canEdit: boolean; busy: boolean; onStart: (budget: number, ids: string[]) => void }) {
  const [budget, setBudget] = useState('10');
  const [selected, setSelected] = useState<string[]>([]);
  const amount = Number(budget);
  const valid = Number.isFinite(amount) && amount >= 0.1 && amount <= 100;
  return <section className="panel run-form"><div className="section-heading"><div><div className="eyebrow">ON-DEMAND EXTRACTION</div><h2>Read the experimental evidence</h2></div><CircleDollarSign className="teal" size={25} /></div><p className="muted">A run reads the chosen PDFs, inspects tables and figures, and records evidence with each measurement. The weekly literature check does not start paid extraction.</p><div className="form-grid"><Field label="Run budget (USD)" hint="Your initial API ceiling is $100. The server enforces the remaining allowance."><div className="input-prefix"><span>$</span><input type="number" value={budget} min="0.1" max="100" step="0.1" onChange={e => setBudget(e.target.value)} disabled={!canEdit} /></div></Field><Field label="Documents"><select value={selected.length === 1 ? selected[0] : ''} disabled={!canEdit} onChange={e => setSelected(e.target.value ? [e.target.value] : [])}><option value="">All uploaded documents ({documents.length})</option>{documents.map(item => <option value={item.id} key={item.id}>{item.filename}</option>)}</select></Field></div>{!valid && <Notice kind="warning">Choose a run limit between $0.10 and $100.</Notice>}<div className="panel-footer"><small>{canEdit ? 'An explicit run is required before any model usage.' : 'You have read-only access to this review.'}</small><button className="button primary" disabled={!canEdit || busy || !documents.length || !valid} onClick={() => onStart(amount, selected)}><Play size={16} />{busy ? 'Starting…' : 'Start extraction'}<ArrowRight size={16} /></button></div></section>;
}
export function RunHistory({ runs, canEdit, busy, onCancel, onResume }: { runs: Run[]; canEdit: boolean; busy: boolean; onCancel: (id: string) => void; onResume: (id: string) => void }) {
  return <section className="panel"><div className="section-heading"><h2>Extraction runs</h2><span className="count-pill">{runs.length}</span></div>{!runs.length ? <Empty title="No extraction runs yet">Upload PDFs and start a run with a spending limit. Results will appear here as the agents work.</Empty> : <div className="run-list">{[...runs].sort((a, b) => b.created_at.localeCompare(a.created_at)).map(run => {
    const progress = progressInfo(run.progress);
    const active = ['running', 'queued'].includes(run.status);
    return <article className="run-card" key={run.id}><div className="run-top"><div><Badge value={run.status} /><span className="run-date">{date(run.created_at)}</span></div><div className="run-cost">{money(run.spent_usd)}<span> / {money(run.budget_usd)}</span></div></div>{active && <><div className="progress-label"><span>{progress.label}</span>{progress.percent != null && <span>{Math.round(progress.percent)}%</span>}</div><div className={`progress-track ${progress.percent == null ? 'indeterminate' : ''}`}><div style={{ width: progress.percent == null ? '35%' : `${progress.percent}%` }} /></div></>}{run.reserved_usd > 0 && <p className="small muted">{money(run.reserved_usd)} reserved for work in progress.</p>}{run.error && <Notice kind="warning">{run.error}</Notice>}<div className="run-bottom"><code>{run.id.slice(0, 12)}</code>{canEdit && active && <button className="button small" disabled={busy} onClick={() => onCancel(run.id)}><Pause size={14} />Cancel run</button>}{canEdit && ['failed', 'cancelled', 'budget_exhausted'].includes(run.status) && <button className="button small" disabled={busy} onClick={() => onResume(run.id)}><RotateCcw size={14} />Resume within allowance</button>}</div><JsonDetails value={run.result} label="Extraction summary and abstentions" /></article>;
  })}</div>}</section>;
}
